Update plume_CI_test.yml

diff --git a/.github/workflows/plume_CI_test.yml b/.github/workflows/plume_CI_test.yml
--- a/.github/workflows/plume_CI_test.yml
+++ b/.github/workflows/plume_CI_test.yml
@@ -64,3 +64,46 @@ jobs:
             
       - name: Display Current Directory Again
         run: echo "Current directory:" $(pwd)
+
+      
+      - name: Parse compilable percentage
+        id: parse_compilable_percentage
+        run: |
+          grep 'Fully successful from minimization to compilation' $(pwd)/ASHE/logs/specimin_statistics.txt | awk '{print $NF}' > compilable_percentage.txt
+          cat compilable_percentage.txt
+        continue-on-error: true
+
+      - name: Check for monotonically increasing compilable percentage
+        run: |
+          current_percentage=$(cat compilable_percentage.txt)
+          echo "Current compilable percentage: $current_percentage"
+          prev_percentage=${{ secrets.PREV_COMPILABLE_PERCENTAGE }}
+          echo "Previous compilable percentage: $prev_percentage"
+          if (( $(echo "$current_percentage < $prev_percentage" |bc -l) )); then
+            echo "Error: Compilable percentage is not increasing."
+            exit 1
+          fi
+        env:
+          prev_percentage: ${{ secrets.PREV_COMPILABLE_PERCENTAGE }}
+
+      - name: Update Previous Compilable Percentage
+        if: success()
+        run: echo "${{ steps.parse_compilable_percentage.outputs.current_percentage }}" > prev_compilable_percentage.txt
+        env:
+          prev_percentage: ${{ secrets.PREV_COMPILABLE_PERCENTAGE }}
+
+      - name: Upload compilable percentage
+        if: always()  # Ensure this step runs even if previous steps fail
+        uses: actions/upload-artifact@v2
+        with:
+          name: compilable-percentage
+          path: compilable_percentage.txt
+
+      - name: Upload previous compilable percentage
+        if: always()  # Ensure this step runs even if previous steps fail
+        uses: actions/upload-artifact@v2
+        with:
+          name: prev-compilable-percentage
+          path: prev_compilable_percentage.txt
+
+
