Update specimin_evaluation_CI.yml

diff --git a/.github/workflows/specimin_evaluation_CI.yml b/.github/workflows/specimin_evaluation_CI.yml
--- a/.github/workflows/specimin_evaluation_CI.yml
+++ b/.github/workflows/specimin_evaluation_CI.yml
@@ -1,4 +1,4 @@
-name: specimin_evaluation_CI 
+name: specimin_evaluation_CI
 
 on:
   push:
@@ -13,14 +13,12 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-        
       - name: Checkout repository
         uses: actions/checkout@v2
         with:
           ref: ${{ github.event.pull_request.head.sha }}
           fetch-depth: 0
 
-    
       - name: Set up environment
         uses: actions/setup-python@v2
         with:
@@ -54,72 +52,46 @@ jobs:
             exit 1
           fi
 
-
-      - name: Download and prepare git-clone-related script
+      - name: Download, prepare, and clone ASHE Project using git-clone-related
         run: |
           curl -L -o git-clone-related https://raw.githubusercontent.com/plume-lib/git-scripts/main/git-clone-related
           chmod +x git-clone-related
-
-      - name: Download and prepare additional scripts
-        run: |
-          curl -L -o git-find-fork https://raw.githubusercontent.com/plume-lib/git-scripts/main/git-find-fork
-          curl -L -o git-find-branch https://raw.githubusercontent.com/plume-lib/git-scripts/main/git-find-branch
-          chmod +x git-find-fork git-find-branch
-
-      - name: Clone ASHE Project using git-clone-related
-        run: |
           ./git-clone-related njit-jerse ASHE_Automated-Software-Hardening-for-Entrypoints ASHE
-          
+
       - name: List Files in ASHE Directory
         run: |
           set -ex
           ls -l ASHE
 
-      - name: List Files in ASHE/src/main/resources
+      - name: Check and Rename Properties File
         run: |
           set -ex
-          ls -l ASHE/src/main/resources
+          CONFIG_PATH="ASHE/src/main/resources/config.properties"
+          EXAMPLE_PATH="ASHE/src/main/resources/example.properties"
 
-      - name: Verify example.properties exists
-        run: |
-          set -ex
-          if [ -f ASHE/src/main/resources/example.properties ]; then 
-            echo "example.properties found"
-          else 
-            echo "example.properties not found"
+          if [ -f "$CONFIG_PATH" ]; then
+            echo "config.properties already exists"
+          elif [ -f "$EXAMPLE_PATH" ]; then
+            echo "example.properties found, renaming to config.properties"
+            mv "$EXAMPLE_PATH" "$CONFIG_PATH"
+            if [ -f "$CONFIG_PATH" ]; then
+              echo "config.properties created successfully"
+            else
+              echo "Failed to create config.properties"
+              exit 1
+            fi
+          else
+            echo "Neither config.properties nor example.properties found"
             exit 1
           fi
 
-      - name: Rename example.properties to config.properties file
-        run: |
-          set -ex
-          mv ASHE/src/main/resources/example.properties ASHE/src/main/resources/config.properties
-          if [ -f ASHE/src/main/resources/config.properties ]; then 
-            echo "config.properties created"
-          else 
-            echo "config.properties not created"
-            exit 1
-          fi
-
-      - name: Give write permissions to config.properties
-        run: |
-          set -ex
-          chmod +w ASHE/src/main/resources/config.properties
-          ls -l ASHE/src/main/resources/config.properties
+          chmod +w "$CONFIG_PATH"
+          ls -l "$CONFIG_PATH"
 
       - name: Update ASHE Config File to update SPECIMIN path
         run: |
           set -ex
-          chmod +w ASHE/src/main/resources/config.properties
-          # Update the specimin.tool.path key with the new value
           sed -i 's|^specimin.tool.path=.*|specimin.tool.path='$(pwd)'|' ASHE/src/main/resources/config.properties
-          # Display the updated config.properties file for verification
-          cat ASHE/src/main/resources/config.properties
-
-      - name: Display updated config.properties
-        run: |
-          set -ex
-          cat ASHE/src/main/resources/config.properties
 
       - name: Make all scripts under ashe_scripts executable
         run: |
@@ -139,15 +111,14 @@ jobs:
             $(pwd)/CI_repository_list.csv \
             $(pwd)/ASHE/CI_REPO_CLONE_SPACE \
             $(pwd)/ASHE/src/main/resources/config.properties
-            
+
       - name: Parse accuracy percentage
         id: parse_accuracy_percentage
         run: |
           current_accuracy=$(grep 'Fully successful from minimization to compilation' "$(pwd)/ASHE/logs/specimin_statistics.txt" | awk '{print $NF}')
           echo "Current accuracy: $current_accuracy"
           echo "::set-output name=current_accuracy::$current_accuracy"
-          
-     
+
       - name: Read, update, and set Evaluation Accuracy Variable
         id: read_update_set_variable
         run: |
@@ -159,12 +130,16 @@ jobs:
             previous_run_accuracy=0
           fi
           echo "Previous run accuracy: $previous_run_accuracy"
+          
           if (( $(echo "$current_accuracy > $previous_run_accuracy" | bc -l) )); then
-            echo "Updating LATEST_SPECIMIN_EVAL_PERCENTAGE to $current_accuracy"
+            echo "Updating variable since current accuracy > previous run accuracy."
             echo "::set-output name=update_needed::true"
             echo "::set-output name=new_accuracy::$current_accuracy"
+          elif (( $(echo "$current_accuracy == $previous_run_accuracy" | bc -l) )); then
+            echo "No change in accuracy."
+            echo "::set-output name=update_needed::false"
           else
-            echo "Current accuracy is less than or equal to the previous run accuracy. Failing the workflow."
+            echo "Current accuracy is less than previous run accuracy."
             exit 1
 
       - name: Update GitHub Variable
